### Display Update User - SUCCESS
GET http://localhost:3000/api/account/user HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJ1c2VybmFtZSI6IkFuY0RhbSIsImp0aSI6ImQyN2UyYWEyLTYxYTMtNDg5Yy1iODk4LTZlZDA0NjUyNDM3NyIsImlhdCI6MTc0ODAwODg3MSwiZXhwIjoxNzQ4MDA5MjkxfQ.RE5GEx8bGXlRYYFzArZbRS41NZo2lqaLy0b0x0fbXI4;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImp0aSI6IjhlZjMxOWNjLWUyOWEtNDJkMy1hMTY4LTIwYWE3YmYwYWVmMCIsImlhdCI6MTc0ODAwODM4MCwiZXhwIjoxNzQ4NjEzMTgwfQ.6eKf44G2XTkDPv9hkhC8gf33MlyXm667EgBG9c72fU8;