### login - SUCCESS
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "test@mail.io",
  "password": "Test_1234"
}

### register - SUCCESS
POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
	"firstname": "Jason",
	"lastname": "Toison",
  "email": "testdeur@mail.io",
	"username":	"Jasd_Toi",
  "password": "Test_1234"
}

### register with existing email - ERROR !
POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
  "firstname": "Jason",
  "lastname": "Toison",
  "email": "test@mail.io",
  "username": "Jasd_Toi",
  "password": "Test_1234"
}

### register with existing username - ERROR !
POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
  "firstname": "Jason",
  "lastname": "Toison",
  "email": "letestdelemail@mail.io",
  "username": "AncDam",
  "password": "Test_1234"
}

### Refresh Token
## + Test with insomnia
POST http://localhost:3000/api/auth/refresh-token HTTP/1.1
Cookie: 

### Logout
POST http://localhost:3000/api/auth/logout HTTP/1.1
Cookie: 
