### login - USER
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "test@mail.io",
  "password": "test1234"
}

### Refresh Token
## Test with insomnia
POST http://localhost:3000/api/auth/refresh-token HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJ1c2VybmFtZSI6IkFuY0RhbSIsImp0aSI6IjI0ZTVlMjcwLTM4YzItNDRjZC04MzAyLTVlMTYxYTg2MTA1NCIsImlhdCI6MTc0NzgxODkxMSwiZXhwIjoxNzQ3ODE5MzMxfQ.bj6TbJwtPkmvWQ6AvbskCNxO2odgwwqjyZ5jOTF1Nbw;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwianRpIjoiNzc3ZGM1MTQtZDdhNi00MjQ2LWEzMWEtZDI3YmIxNDNjNzgzIiwiaWF0IjoxNzQ3ODE4OTExLCJleHAiOjE3NDg0MjM3MTF9.5VHPUb202AR0U08HYJZPLBo5NVBpKVbILCAR8ntO_vQ;

### Logout
POST http://localhost:3000/api/auth/logout HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJ1c2VybmFtZSI6IkFuY0RhbSIsImp0aSI6IjI0ZTVlMjcwLTM4YzItNDRjZC04MzAyLTVlMTYxYTg2MTA1NCIsImlhdCI6MTc0NzgxODkxMSwiZXhwIjoxNzQ3ODE5MzMxfQ.bj6TbJwtPkmvWQ6AvbskCNxO2odgwwqjyZ5jOTF1Nbw;

