### login - USER
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "test@mail.io",
  "password": "test1234"
}

### Refresh Token
## Test with insomnia
POST http://localhost:3000/api/auth/refresh-token HTTP/1.1
Cookie: 

### Logout
POST http://localhost:3000/api/auth/logout HTTP/1.1
Cookie: 

