 ### ### GET create
GET http://localhost:3000/api/challenges/create HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJ1c2VybmFtZSI6IlNpeFNtb2tlIiwianRpIjoiNzUyOTNjN2QtZGEwZi00NWJkLWE1OGEtYmRkYmQwZTk0OGM1IiwiaWF0IjoxNzQ4MzMzNzk5LCJleHAiOjE3NDgzMzQyMTl9.m3W9EjvEdO24ujUm_nE-upHbviISdIGdyUWCOpYm09E;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwianRpIjoiNzI1ZjBjOWQtNDQwNC00ZWVkLTg5ZGMtNDZmYjc2ZWFlOWUzIiwiaWF0IjoxNzQ4MzMzNzk5LCJleHAiOjE3NDg5Mzg1OTl9.jbuM6KRnEmapRd59NBvEEQ2tX5LAPcRdIcSdjutJd_A;

### GET Challenges
GET http://localhost:3000/api/challenges?limit=10&currentPage=2&order=createdAt&direction=desc HTTP/1.1

### POST challenges user
POST http://localhost:3000/api/challenges/user HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJ1c2VybmFtZSI6IkFuY0RhbSIsImp0aSI6IjM2YTFjZGI4LTU5ZjEtNGE5OC05NDViLWRmYjAyOTRhZTAxNiIsImlhdCI6MTc0ODU5ODgyMiwiZXhwIjoxNzQ4NTk5MjQyfQ.ImQfwVgmUiKDL2q5VfnCmfJE5I8loSdU9Ktt_oFoZKo;


### GET Challenge by ID
GET http://localhost:3000/api/challenges/1 HTTP/1.1

### POST Challenge Owner
POST http://localhost:3000/api/challenges/owner HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJ1c2VybmFtZSI6IkFuY0RhbSIsImp0aSI6ImUyZjhjZjc5LTAyOTYtNGEyMS1iODZlLWEyNDU2ZWYyNjQyMCIsImlhdCI6MTc0ODQyMzAzNiwiZXhwIjoxNzQ4NDIzNDU2fQ.-XoyoAEg-dLbv5xoRKNFwhz457VxRDY535763rXIpC4;
Content-Type: application/json

{
  "challenge_id": 1
}
 