### GET All participations
GET /api/participations?limit=1&currentPage=1&order=updatedAt&direction=desc HTTP/1.1
Host: localhost:3000

### Get participation leaderboard
GET /api/participations/leaderboard HTTP/1.1
Host: localhost:3000

### GET Count how many participations are in a challenge by challenge ID
GET /api/participations/challenge/8/count HTTP/1.1
Host: localhost:3000


### POST Check user participation
POST /api/participations/check/user HTTP/1.1
Host: localhost:3000
Cookie: access_token=your_access_token_here
Content-Type: application/json

{
  "challenge_id": 8
}

### GET popular challenges
GET /api/participations/popular?limit=5&currentPage=1 HTTP/1.1
Host: localhost:3000

### GET participation by ID
GET /api/participations/8 HTTP/1.1
Host: localhost:3000

### GET participation by challenge ID
GET /api/participations/challenge/4?limit=10&currentPage=1&order=updatedAt&direction=desc HTTP/1.1
Host: localhost:3000